Data = {
    'Мобильный телефон': 79600615828,
    'Электронная почта': 'bagavieva.20154@gmail.com',
    'Логин': 'rtkid_1674141625971',
    'Новый пароль': 'Bagavieva1',
    'Валидный пароль': 'Bagavieva2',
    'Невалидный пароль': '1Nawdtrew',
    'Имя': 'Аделя',
    'Фамилия': 'Багавиева',
    'Невалидный номер телефона': 88888888888,
    'Невалидная электронная почта': '1asssssski@mail.ru',
    'Невалидный логин': 'hdidknwh-lll',
    'Невалидный номер лицевого счёта': 123456789101,
    'Почтовый ящик': 'adkoss.1@mail.ru',
    'Пароль от почтового ящика': 'tAY2IytrpR1^',
    'Логин от янд': 'adarada228@yandex.ru',
    'Пароль от янд': 'Bagavieva1.',
    'Короткий пароль': '1',
    'Валидный логин ВР': 'RTKID_1674141625971',
    'Длинный пароль': 'Ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd1'
}
